# Site settings
title: a cloud never dies
email: om@plumvillage.org
description: > # this means to ignore newlines until "baseurl:"
  Awakening to each moment in community life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: brstream
github_username:  brstream

# Build settings
markdown: kramdown
